AllCops:
  Include:
    - '**/Rakefile'
    - '**/Capfile'
  Exclude:
    - 'db/migrate/**/*'
    - 'vendor/**/*'

Style/LineLength:
  Max: 100

Style/NumericLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/ClassLength:
  Enabled: false

Style/MethodLength:
  Enabled: false
